// Max volume is 1, mute is 0
const INTRO_BLUR = 100;
const RETURN_TO_INTRO_SECONDS = 20
const LOSE_WIN_NOTIFICATION_DELAY_MS = 5000

// VOLUME
const NOTIFICATION_VOLUME = 0.4
const FEEDBACK_VOLUME = 0.6
const BAR_VOLUME = 0.4
const LOSE_WIN_VOLUME = 0.4;

const TUTORIAL_LENGHT_MS = 21000

// GAME
const GOOD_NOTIFICATION_PERCENT = 70 
const BARS_START_PERCENT = 12
const FEEDBACK_PER_PERCENT = 30
const CORRECT_ANSWER_PT = 10
const WRONG_ASNWER_PT = -7
const CORRECT_TRASH_ANSWER_PT = 5

// BAR HEALT 
const BAR_LOSING_PT = 0.025
const BAR_LOSING_SPEED_MS = 50

const START_NOTE_SPANW_SPEED_MS = 1200 //Spawning notification every 1000ms wich is 1s
const END_NOTE_SPANW_SPEED_MS = 500 //Spawning notification every 500ms wich is 0.5s
const NOTE_SPAWN_ACCELERATOR = 25 